### ISSUE TITLE
OAuth for Java 

### ISSUE THREAD

**Issue by bb-checkpay** [plaid/tutorial-resources#21]
It would be great to add 0Auth for Java as well. 
THanks

**Comment by phoenixy1** [comment]
Thanks for the suggestion! Closing this out as we probably won't add this:
For client-side Java, see https://github.com/plaid/plaid-link-android for an example implementation.
For server-side Java, see the Quickstart https://plaid.com/docs/quickstart/ (we don't really plan to add additional server languages for the OAuth demos as 99% of the interesting implementation happens on the client side)
