### ISSUE TITLE
Issue with Production credentials

### ISSUE THREAD

**Issue by thomas66777** [plaid/tutorial-resources#33]
it works when using sandbox, but when using production getting error on popup after clicking "connect my bank".
This used to work for me last month and now it no longer works, I check my account to make sure my API keys are still the same.

{"error_type":"API_ERROR","error_code":"INTERNAL_SERVER_ERROR","error_message":"an unexpected error occurred","display_message":"","request_id":""}

**Comment by phoenixy1** [comment]
This doesn't seem to be specific to the tutorial resources repo -- please go ahead and file a support ticket via the Dashboard if you need assistance with this issue.
